# TheEvilShadoo's make.conf
# Source external files
NTHREADS="auto"
source /usr/share/fetchcommandwrapper/make.conf

# My custom flags
COMMON_FLAGS="-march=native -O2 -pipe -mtls-dialect=gnu2"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -fuse-ld=mold"
USE="-emacs -gnome -systemd -X \
     appindicator jemalloc mimalloc offensive pipewire pulseaudio screencast tcmalloc truetype \
     vaapi wayland"

# System variables
ABI_X86="64"
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="-* @FREE"
BINPKG_COMPRESS="lz4"
BINPKG_FORMAT="gpkg"
CMAKE_MAKEFILE_GENERATOR="ninja"
CPU_FLAGS_X86="aes avx avx2 avx512_bf16 avx512_bitalg avx512_vbmi2 avx512_vnni avx512_vpopcntdq avx512bw avx512cd avx512dq avx512f avx512ifma avx512vbmi avx512vl bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 vpclmulqdq"
DISTDIR="/var/cache/distfiles"
EMERGE_DEFAULT_OPTS="--autounmask=y --autounmask-write=y --color=y --jobs=16 --keep-going=y --load-average=16 --jobs-tmpdir-require-free-gb=0"
FEATURES="candy getbinpkg parallel-fetch parallel-install -ebuild-locks -merge-wait"
GRUB_PLATFORMS="efi-64"
INPUT_DEVICES="libinput"
L10N="en-US"
LC_MESSAGES="C"
LINGUAS="en-US"
MAKEOPTS="-j16 -l16"
PKGDIR="/var/cache/binpkgs"
PORTAGE_SCHEDULING_POLICY="idle"
PORTDIR="/var/db/repos/gentoo"
VIDEO_CARDS="amdgpu radeonsi"

GENTOO_MIRRORS="https://104.18.6.32/gentoo/ \
    https://gentoo.kurdy.org/ \
    https://mirror.keiminem.com/gentoo/ \
    https://104.21.5.48/gentoo/ \
    https://mirrors.mit.edu/gentoo-distfiles/ \
    https://mirror.planetunix.net/pub/gentoo/ \
    https://mirror.reenigne.net/gentoo/ \
    https://172.67.165.93/ \
    https://mirror.leaseweb.com/gentoo/ \
    https://gentoo.mirrors.ovh.net/gentoo-distfiles/"
