# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[mv]
location = /var/db/repos/mv
sync-type = git
sync-uri = https://anongit.gentoo.org/git/user/mv.git

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git

[CachyOS-kernels]
location = /var/db/repos/CachyOS-kernels
sync-type = git
sync-uri = https://github.com/Szowisz/CachyOS-kernels.git

[without-systemd]
location = /var/db/repos/without-systemd
sync-type = git
sync-uri = https://github.com/KenjiBrown/without-systemd.git

[another-brave-overlay]
location = /var/db/repos/another-brave-overlay
sync-type = git
sync-uri = https://github.com/falbrechtskirchinger/another-brave-overlay.git

[edgets]
location = /var/db/repos/edgets
sync-type = git
sync-uri = https://github.com/BlueManCZ/edgets.git

[hyproverlay]
location = /var/db/repos/hyproverlay
sync-type = git
sync-uri = https://codeberg.org/hyproverlay/hyproverlay.git

[xarblu-overlay]
location = /var/db/repos/xarblu-overlay
sync-type = git
sync-uri = https://github.com/xarblu/xarblu-overlay.git
