#!/bin/sh

# Displays number of upgradeable packages.
# For this to work, have a `emerge --sync` command run in the background as a
# cronjob every so often as root. This script will then read those packages.
# When clicked, it will run an upgrade via pacman.

case $BLOCK_BUTTON in
    1) notify-send "`eix-installed all | tail -n1`" ;;
	3) notify-send "🎁 Upgrade module" "📦: Number of upgradable packages" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

emerge -upq @world | grep -Fcv "[ignored]" | sed "s/^/📦 /;s/^📦0$//g"
