preload = /home/ryan/pictures/wallpapers/3d-network.jpg
preload = /home/ryan/pictures/irl/Fuzzcracker.png
wallpaper = DP-1,/home/ryan/pictures/wallpapers/3d-network.jpg
wallpaper = HDMI-A-1,/home/ryan/pictures/irl/Fuzzcracker.png
splash = true
