# Auth and Environment
exec-once = /usr/libexec/hyprpolkitagent
exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /home/ryan/.config/hypr/scripts/XDPH.sh
exec-once = xrandr --output eDP-1 --primary

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Auto delete trash 30 days old
exec-once = trash-empty 30

# Theme
exec-once = hyprctl setcursor $cursorTheme $cursorSize
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize
exec-once = gsettings set org.gtk.Settings.FileChooser window-size '(800,600)'
exec-once = gsettings set org.gnome.desktop.interface icon-theme "Dracula"
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
exec-once = gsettings set org.gnome.desktop.wm.preferences theme "Dracula"

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy

# EasyEffects equalizer
exec-once = ~/.config/hypr/easyeffectsstartup.sh

# Terminal server
exec-once = foot --server

# Lighting
exec-once = openrgb --startminimized -p Dracula
exec-once = ckb-next -b

# OpenTabletDriver
#exec-once = otd

# EasyEffects
exec-once = ~/.config/hypr/scripts/easyeffectsstartup.sh

# Resize and move windows based on matches (e.g. pip)
exec-once = caelestia resizer -d

# Start shell and then apps dependent on it
exec-once = caelestia shell -d && (steam -silent & keepassxc & gammastep-indicator & sleep 1 && /home/ryan/.local/bin/vesktop)
